"""denormalize_intelligence_data

Revision ID: 1577beb508d6
Revises: 5acba6ba7863
Create Date: 2026-01-27 18:39:32.312358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '1577beb508d6'
down_revision: Union[str, None] = '5acba6ba7863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_jobs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_entity_jobs_job_id'))
        batch_op.drop_index(batch_op.f('ix_entity_jobs_status'))

    op.drop_table('entity_jobs')
    op.drop_table('image_intelligence')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intelligence_data', sa.JSON(), nullable=True))

    with op.batch_alter_table('entities_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intelligence_data', sa.JSON(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entities_version', schema=None) as batch_op:
        batch_op.drop_column('intelligence_data')

    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_column('intelligence_data')

    op.create_table('image_intelligence',
    sa.Column('entity_id', sa.INTEGER(), nullable=False),
    sa.Column('md5', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('face_detection_job_id', sa.VARCHAR(), nullable=True),
    sa.Column('clip_job_id', sa.VARCHAR(), nullable=True),
    sa.Column('dino_job_id', sa.VARCHAR(), nullable=True),
    sa.Column('face_embedding_job_ids', sqlite.JSON(), nullable=True),
    sa.Column('processing_status', sa.VARCHAR(), nullable=False),
    sa.Column('image_path', sa.TEXT(), nullable=False),
    sa.Column('version', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('entity_jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('entity_id', sa.INTEGER(), nullable=False),
    sa.Column('job_id', sa.VARCHAR(), nullable=False),
    sa.Column('task_type', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', sa.INTEGER(), nullable=False),
    sa.Column('completed_at', sa.INTEGER(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_jobs_job_id'), ['job_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_entity_jobs_entity_id'), ['entity_id'], unique=False)

    # ### end Alembic commands ###
