"""remove_face_match_table

Revision ID: 5acba6ba7863
Revises: e52a818f09f0
Create Date: 2026-01-24 23:51:55.907124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5acba6ba7863'
down_revision: Union[str, None] = 'e52a818f09f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('face_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_face_matches_face_id'))
        batch_op.drop_index(batch_op.f('ix_face_matches_matched_face_id'))

    op.drop_table('face_matches')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_matches',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('face_id', sa.INTEGER(), nullable=False),
    sa.Column('matched_face_id', sa.INTEGER(), nullable=False),
    sa.Column('similarity_score', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['face_id'], ['faces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_face_id'], ['faces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('face_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_face_matches_matched_face_id'), ['matched_face_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_face_matches_face_id'), ['face_id'], unique=False)

    # ### end Alembic commands ###
