"""consolidate_models_and_add_job_tracking

Revision ID: 6d29391ba950
Revises: 00268ae3f7cc
Create Date: 2026-01-22 16:06:07.595230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '6d29391ba950'
down_revision: Union[str, None] = '00268ae3f7cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queue_entries_enqueued_at'), table_name='queue_entries')
    op.drop_index(op.f('ix_queue_entries_job_id'), table_name='queue_entries')
    op.drop_table('queue_entries')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_by'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_table('jobs')
    op.create_index(op.f('ix_entities_parent_id'), 'entities', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'entities', 'entities', ['parent_id'], ['id'])
    op.create_index(op.f('ix_entities_version_parent_id'), 'entities_version', ['parent_id'], unique=False)
    op.add_column('image_intelligence', sa.Column('face_detection_job_id', sa.String(), nullable=True))
    op.add_column('image_intelligence', sa.Column('clip_job_id', sa.String(), nullable=True))
    op.add_column('image_intelligence', sa.Column('dino_job_id', sa.String(), nullable=True))
    op.add_column('image_intelligence', sa.Column('processing_status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_intelligence', 'processing_status')
    op.drop_column('image_intelligence', 'dino_job_id')
    op.drop_column('image_intelligence', 'clip_job_id')
    op.drop_column('image_intelligence', 'face_detection_job_id')
    op.drop_index(op.f('ix_entities_version_parent_id'), table_name='entities_version')
    op.drop_constraint(None, 'entities', type_='foreignkey')
    op.drop_index(op.f('ix_entities_parent_id'), table_name='entities')
    op.create_table('jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_id', sa.VARCHAR(), nullable=False),
    sa.Column('task_type', sa.VARCHAR(), nullable=False),
    sa.Column('priority', sa.INTEGER(), nullable=False),
    sa.Column('params', sqlite.JSON(), nullable=False),
    sa.Column('output', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('progress', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.INTEGER(), nullable=False),
    sa.Column('started_at', sa.INTEGER(), nullable=True),
    sa.Column('completed_at', sa.INTEGER(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('retry_count', sa.INTEGER(), nullable=False),
    sa.Column('max_retries', sa.INTEGER(), nullable=False),
    sa.Column('created_by', sa.VARCHAR(), nullable=True),
    sa.Column('updated_at', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_job_id'), 'jobs', ['job_id'], unique=1)
    op.create_index(op.f('ix_jobs_created_by'), 'jobs', ['created_by'], unique=False)
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_table('queue_entries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_id', sa.VARCHAR(), nullable=False),
    sa.Column('priority', sa.INTEGER(), nullable=False),
    sa.Column('enqueued_at', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_entries_job_id'), 'queue_entries', ['job_id'], unique=1)
    op.create_index(op.f('ix_queue_entries_enqueued_at'), 'queue_entries', ['enqueued_at'], unique=False)
    # ### end Alembic commands ###
