"""initial

Revision ID: 7662b31daa39
Revises: 
Create Date: 2025-12-02 12:41:20.168720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7662b31daa39'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_collection', sa.Boolean(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('added_date', sa.BigInteger(), nullable=True),
    sa.Column('updated_date', sa.BigInteger(), nullable=True),
    sa.Column('create_date', sa.BigInteger(), nullable=True),
    sa.Column('added_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('extension', sa.String(), nullable=True),
    sa.Column('md5', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_md5'), 'entities', ['md5'], unique=True)
    op.create_table('entities_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('is_collection', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('label', sa.String(), autoincrement=False, nullable=True),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('added_date', sa.BigInteger(), autoincrement=False, nullable=True),
    sa.Column('updated_date', sa.BigInteger(), autoincrement=False, nullable=True),
    sa.Column('create_date', sa.BigInteger(), autoincrement=False, nullable=True),
    sa.Column('added_by', sa.String(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('height', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('width', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('mime_type', sa.String(), autoincrement=False, nullable=True),
    sa.Column('type', sa.String(), autoincrement=False, nullable=True),
    sa.Column('extension', sa.String(), autoincrement=False, nullable=True),
    sa.Column('md5', sa.String(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.String(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_entities_version_end_transaction_id'), 'entities_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_entities_version_md5'), 'entities_version', ['md5'], unique=False)
    op.create_index(op.f('ix_entities_version_operation_type'), 'entities_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_entities_version_transaction_id'), 'entities_version', ['transaction_id'], unique=False)
    op.create_table('service_config',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('transaction',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('remote_addr', sa.String(length=50), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('service_config')
    op.drop_index(op.f('ix_entities_version_transaction_id'), table_name='entities_version')
    op.drop_index(op.f('ix_entities_version_operation_type'), table_name='entities_version')
    op.drop_index(op.f('ix_entities_version_md5'), table_name='entities_version')
    op.drop_index(op.f('ix_entities_version_end_transaction_id'), table_name='entities_version')
    op.drop_table('entities_version')
    op.drop_index(op.f('ix_entities_md5'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
