"""initial_schema

Revision ID: bee9c3df9036
Revises: 
Create Date: 2026-01-23 12:46:07.946833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bee9c3df9036'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_collection', sa.Boolean(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('added_date', sa.BigInteger(), nullable=True),
    sa.Column('updated_date', sa.BigInteger(), nullable=True),
    sa.Column('create_date', sa.BigInteger(), nullable=True),
    sa.Column('added_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('extension', sa.String(), nullable=True),
    sa.Column('md5', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entities_md5'), ['md5'], unique=True)
        batch_op.create_index(batch_op.f('ix_entities_parent_id'), ['parent_id'], unique=False)

    op.create_table('entities_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('is_collection', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('label', sa.String(), autoincrement=False, nullable=True),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('added_date', sa.BigInteger(), autoincrement=False, nullable=True),
    sa.Column('updated_date', sa.BigInteger(), autoincrement=False, nullable=True),
    sa.Column('create_date', sa.BigInteger(), autoincrement=False, nullable=True),
    sa.Column('added_by', sa.String(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('height', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('width', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('mime_type', sa.String(), autoincrement=False, nullable=True),
    sa.Column('type', sa.String(), autoincrement=False, nullable=True),
    sa.Column('extension', sa.String(), autoincrement=False, nullable=True),
    sa.Column('md5', sa.String(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.String(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    with op.batch_alter_table('entities_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entities_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_version_md5'), ['md5'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_version_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('entity_sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('known_persons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('known_persons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_known_persons_name'), ['name'], unique=False)

    op.create_table('known_persons_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.BigInteger(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.BigInteger(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    with op.batch_alter_table('known_persons_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_known_persons_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_known_persons_version_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_known_persons_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_known_persons_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('service_config',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('transaction',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('remote_addr', sa.String(length=50), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_changes',
    sa.Column('transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('entity_name', sa.Unicode(length=255), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id', 'entity_name')
    )
    op.create_table('entity_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('completed_at', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_jobs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_jobs_job_id'), ['job_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_entity_jobs_status'), ['status'], unique=False)

    op.create_table('faces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('bbox', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('landmarks', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('known_person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['known_person_id'], ['known_persons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faces_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_faces_known_person_id'), ['known_person_id'], unique=False)

    op.create_table('image_intelligence',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('md5', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('face_detection_job_id', sa.String(), nullable=True),
    sa.Column('clip_job_id', sa.String(), nullable=True),
    sa.Column('dino_job_id', sa.String(), nullable=True),
    sa.Column('face_embedding_job_ids', sa.JSON(), nullable=True),
    sa.Column('processing_status', sa.String(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('face_matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('face_id', sa.Integer(), nullable=False),
    sa.Column('matched_face_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['face_id'], ['faces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_face_id'], ['faces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('face_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_face_matches_face_id'), ['face_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_face_matches_matched_face_id'), ['matched_face_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('face_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_face_matches_matched_face_id'))
        batch_op.drop_index(batch_op.f('ix_face_matches_face_id'))

    op.drop_table('face_matches')
    op.drop_table('image_intelligence')
    with op.batch_alter_table('faces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faces_known_person_id'))
        batch_op.drop_index(batch_op.f('ix_faces_entity_id'))

    op.drop_table('faces')
    with op.batch_alter_table('entity_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_entity_jobs_job_id'))
        batch_op.drop_index(batch_op.f('ix_entity_jobs_entity_id'))

    op.drop_table('entity_jobs')
    op.drop_table('transaction_changes')
    op.drop_table('transaction')
    op.drop_table('service_config')
    with op.batch_alter_table('known_persons_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_known_persons_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_known_persons_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_known_persons_version_name'))
        batch_op.drop_index(batch_op.f('ix_known_persons_version_end_transaction_id'))

    op.drop_table('known_persons_version')
    with op.batch_alter_table('known_persons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_known_persons_name'))

    op.drop_table('known_persons')
    op.drop_table('entity_sync_state')
    with op.batch_alter_table('entities_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entities_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_entities_version_parent_id'))
        batch_op.drop_index(batch_op.f('ix_entities_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_entities_version_md5'))
        batch_op.drop_index(batch_op.f('ix_entities_version_end_transaction_id'))

    op.drop_table('entities_version')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entities_parent_id'))
        batch_op.drop_index(batch_op.f('ix_entities_md5'))

    op.drop_table('entities')
    # ### end Alembic commands ###
