"""Standardize intelligence table: rename image_id to entity_id

Revision ID: e52a818f09f0
Revises: bee9c3df9036
Create Date: 2026-01-24 09:24:08.225459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e52a818f09f0'
down_revision: Union[str, None] = 'bee9c3df9036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_intelligence', schema=None) as batch_op:
        batch_op.alter_column('image_id', new_column_name='entity_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_intelligence', schema=None) as batch_op:
        batch_op.alter_column('entity_id', new_column_name='image_id')
    # ### end Alembic commands ###
